version: '3.9'

services:

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    env_file:
      - ./app/.env

  web:
    build: .
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    depends_on:
      - db
    expose:
      - 8000
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
      - ./app/media:/app/media
    depends_on:
      - web

volumes:
  pgdata:
