# Generated by Django 5.2 on 2025-04-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_resetuserpasswordcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resetuserpasswordcode",
            old_name="is_used",
            new_name="is_verified",
        ),
    ]
