# Generated by Django 5.2 on 2025-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_is_used_resetuserpasswordcode_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetuserpasswordcode",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resetuserpasswordcode",
            name="verified_expire_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
