# Generated by Django 5.2 on 2025-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_resetuserpasswordcode_is_password_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetuserpasswordcode",
            name="is_deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
