# Generated by Django 5.2 on 2025-04-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                related_name="links",
                related_query_name="link",
                to="links.linkcollection",
            ),
        ),
    ]
