# Generated by Django 5.2 on 2025-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_alter_link_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="load_status",
            field=models.CharField(
                choices=[
                    ("loaded", "loaded"),
                    ("not_loaded", "not_loaded"),
                    ("error", "error"),
                ],
                default="not_loaded",
                max_length=20,
            ),
        ),
    ]
