# Generated by Django 5.2 on 2025-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_link_load_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="image_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("website", "website"),
                    ("book", "book"),
                    ("article", "article"),
                    ("music", "music"),
                    ("video", "video"),
                ],
                default=None,
                max_length=60,
                null=True,
            ),
        ),
    ]
