# Generated by Django 5.2 on 2025-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_alter_link_description_alter_link_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="parsed_url",
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
